

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.UIManager.get;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
 public class Returnbook extends javax.swing.JInternalFrame {
      PreparedStatement ps;
    Connection conn = MyConnection.getConnection();
    ResultSet rs;
      

    /**
     * Creates new form AddLibrarian
     */
    public Returnbook() {
        initComponents();
       IssueBook1 i = new IssueBook1();
       
        i.displayTable(jTable1);
       
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jreturn = new javax.swing.JButton();
        jreturn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 496));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Student ID", "Issued Date", "Returning Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 480, 420));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Student ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, 30));

        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
        });
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Book ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 170, 30));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 190, 30));

        jreturn.setBackground(new java.awt.Color(255, 153, 153));
        jreturn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jreturn.setText("RETURN");
        jreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreturnActionPerformed(evt);
            }
        });
        getContentPane().add(jreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 50));

        jreturn1.setBackground(new java.awt.Color(153, 255, 153));
        jreturn1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jreturn1.setText("RESET");
        jreturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreturn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jreturn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 180, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1010, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

   
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         //TODO add your handling code here:
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sidKeyReleased

   
        

    
    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyReleased

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
         

        
    }//GEN-LAST:event_idKeyPressed

    private void jreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreturnActionPerformed
        // TODO add your handling code here:
          try {
            String s = id.getText();
            String m = sid.getText();
            String abc = "delete from issuebook where bookid='" + s + "' AND studentid='" + m + "'";
            ps = conn.prepareStatement(abc);
            PreparedStatement pst1;
            pst1 = conn.prepareStatement("UPDATE `addbook` SET `availability` = 'yes', `returningdate` = '---' WHERE `addbook`.`bookid` ='" + s + "'");

            if (ps.executeUpdate() > 0 && pst1.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "The book is returned");

            } else {
                JOptionPane.showMessageDialog(null, "Wrong book id or student id");
            }
            IssueBook1 i = new IssueBook1();
            i.displayTable(jTable1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
           
    
        
    }//GEN-LAST:event_jreturnActionPerformed

    private void jreturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreturn1ActionPerformed
        // TODO add your handling code here:
        id.setText("");
        sid.setText("");
    }//GEN-LAST:event_jreturn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jreturn;
    private javax.swing.JButton jreturn1;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables

}
